apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy91
  labels:
    app: autodeploy91
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718793519981
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy91
  template:
    metadata:
      labels:
        app: autodeploy91
    spec:
      containers:
        - name: autodeploy91
          image: acrworkflow1718793519981.azurecr.io/image-workflow-1718793519981:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
