apiVersion: v1
kind: Service
metadata:
  name: autodeploy91
  namespace: namespace-workflow-1718793519981
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy91
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000